upstream teamabs_backends {
    server 10.7.21.236:3001;
    server 10.7.16.91:3002;
}

server {
    listen 8080;
    server_name app.teamabs.test;

    location / {
        proxy_pass http://teamabs_backends;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 8443 ssl;
    server_name app.teamabs.test;

    ssl_certificate /opt/homebrew/etc/nginx/ssl/app.teamabs.test.crt;
    ssl_certificate_key /opt/homebrew/etc/nginx/ssl/app.teamabs.test.key;

    location / {
        proxy_pass http://teamabs_backends;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
