# Listen on Mac 1's LAN interface/IP
listen-address=10.7.21.236
interface=en0
bind-interfaces

# DNS port
port=53

# Project DNS records
address=/app.teamabs.test/10.7.9.208
address=/api.teamabs.test/10.7.9.208

# Forward all other DNS queries to normal DNS servers
server=1.1.1.1
server=8.8.8.8